user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    access_log    off;
    sendfile      on;
    server_tokens off;

    # Listen on 443 (Azure injects TLS)
    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate     /etc/ssl/certs/azure.pem;
        ssl_certificate_key /etc/ssl/private/azure.key;

        include /etc/nginx/conf.d/*.conf;
    }
}